accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_page, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout')
]

railway/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('train.urls'))
]

urlpatterns += staticfiles_urlpatterns()

train/urls.py
from django.urls import path
from . import views


app_name = 'train'

urlpatterns = [
    path('home/', views.home_page, name='home'),

]

accounts/models.py
from django.db import models

# Create your models here.

train/models.py
from django.db import models


class Train(models.Model):
    train_no = models.IntegerField(default=None, blank=True, null=True)
    train_name = models.CharField(max_length=50)

    def __str__(self):
        return self.train_name


class Station(models.Model):
    station_id = models.IntegerField(default=None, blank=True, null=True)
    station_name = models.CharField(max_length=50, blank=True)
    train_no = models.ForeignKey(Train, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.station_name

train/forms.py
from django import forms


class NameForm(forms.Form):
    start_station = forms.CharField(label='Origin', max_length=100)
    dest_station = forms.CharField(label='Destination', max_length=100)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


def signup_page(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            #redirect to right place
            return redirect('accounts:login')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup_page.html', {'form': form})


def login_page(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            #redirect to correct place
            return redirect('accounts:login')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login_page.html', {'form': form})


def logout_page(request):
    if request.method == 'POST':
        logout(request)
    return redirect(request, 'accounts:login')

train/views.py
from django.shortcuts import render, redirect
from .forms import NameForm


def home_page(request):
    if request.method == 'POST':
        form = NameForm(request.POST)
        if form.is_valid():
            # search db
            return render(request, 'accounts/login', {'form': form})
    else:
        form = NameForm()
    return render(request, 'train/home_page.html', {'form': form})

accounts/templates/accounts/login_page.html
{% extends 'base_template.html' %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Login">
</form>

{% endblock %}

accounts/templates/accounts/signup_page.html
{% extends 'base_template.html' %}
{% block content %}
<div class = 'test'>
    <form method="post">
        {% csrf_token %}
        {{form}}
        <br>
        <input type="submit" value="Signup">
    </form>
</div>
{% endblock %}

templates/base_template.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
 <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	 <link rel="stylesheet" href="{% static 'css/my_styles.css' %}">
    <title>Railway</title>
 </head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'train:home' %}">Railway</a>
  <div class="my_signup_login">
  <a type="button" class="btn btn-outline-success my_signup" href="{% url 'accounts:signup' %}">Signup</a>
  <a type="button" class="btn btn-outline-success" href="{% url 'accounts:login' %}">Login</a>
  </div>
</nav>
{% block content %}
{% endblock %}
<footer>
	<div class="social-footer">
		<div class="center">
			<img src="/static/img/twitter.png" height="48" width="55">
		</div>
	</div>
	<div class="social-footer">
		<div class="center">
			<img src="/static/img/facebook.png" height="55" width="28">
		</div>
	</div>
	<div class="social-footer">
		<div class="center">
			<img src="/static/img/instagram.png" height="52" width="52">
		</div>
	</div>
</footer>
</body>
<script type="text/javascript" src="/static/js/jquery-3.4.1.slim.min.js"></script>
<script type="text/javascript" src="/static/js/popper.min.js"></script>
<script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
</html>

train/templates/train/home_page.html
{% extends 'base_template.html' %}

{% block content %}
<form class="center"  method="post">
    {% csrf_token %}
    {{ form }}
    <div class="center" ><input type="submit" value="Search"></div>
</form>
{% endblock %}